#!/bin/bash
raw=$(jq -r '.name + "|" + ([.types[].type.name] | join(",")) + "|" + (.weight|tostring) + "|" + (.height|tostring)' data.json)
#use awk and sed to clean and transform
name=$(echo "$raw" | awk -F'|' '{print $1}' | sed 's/.*/\u&/')
type=$(echo "$raw" | awk -F'|' '{print $2}' | sed 's/\b./\u&/g')
weight=$(echo "$raw" | awk -F'|' '{print $3}')
height=$(echo "$raw" | awk -F'|' '{print $4}')

# covert weight and height to correct unit
formatted_weight=$(awk -v w="$weight" 'BEGIN {w=w/10; printf"%g", w}')
formatted_height=$(awk -v h="$height" 'BEGIN {h=h/10; printf"%g", h}')

# print out the result
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
